# Generated by Django 2.2.7 on 2019-12-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='file',
            new_name='download',
        ),
    ]
