# Generated by Django 2.2.7 on 2020-02-07 11:43

from datetime import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20200207_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.now, verbose_name='添加时间'),
        ),
    ]
