# Generated by Django 2.2.7 on 2020-02-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20200212_1115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTag',
        ),
    ]
