# Generated by Django 2.2.7 on 2020-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_delete_coursetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
    ]
