# Generated by Django 2.2.7 on 2020-02-12 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20200212_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
    ]
