# Generated by Django 2.2.7 on 2020-02-12 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200212_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
    ]
