# Generated by Django 2.2.7 on 2020-02-12 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
    ]
