# Generated by Django 2.2.7 on 2020-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
    ]
