# Generated by Django 2.2.7 on 2020-02-12 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20200212_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='创建的时间'),
        ),
    ]
