# Generated by Django 2.2.7 on 2020-02-12 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20200212_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userask',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建的时间'),
        ),
    ]
