# Generated by Django 2.2.7 on 2020-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20200107_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='points',
            field=models.CharField(default='', max_length=50, verbose_name='教学特点'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='公司职位'),
        ),
    ]
