# Generated by Django 2.2.7 on 2020-02-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20200203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建的时间'),
        ),
    ]
