# Generated by Django 2.2.7 on 2020-02-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20200212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='datetime',
            field=models.DateTimeField(verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='datetime',
            field=models.DateTimeField(verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='datetime',
            field=models.DateTimeField(verbose_name='创建的时间'),
        ),
    ]
