# Generated by Django 2.2.7 on 2020-02-12 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20200212_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 12, 18, 38, 21, 580792), verbose_name='创建的时间'),
        ),
    ]
